typography_spectrum: 0.7598952101543546
content_rating:
  adult: false
color:
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  brandStrength: 0.948826810810715
  lightness: 0.4701058885548264
  saturation: 0.033744634129107
  rhythmicContrast: 0.41073624859564006
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.6313266640063375
author:
  name: Morten Pradsgaard
  url: ''
  email: mortenprads@gmail.com
name: LifeDoc
title: LifeDoc
description: Billeder fra livet
